service: provisioning-steps-java

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  environment:
    #reference the output variable mailboxDynamoDbTableName defined in provisioning-steps project (in the appropriate stage)
    DYNAMODB_TABLE_MBOX: ${cf:provisioning-steps-${opt:stage, self:provider.stage}.mailboxesDynamoDbTableName} 
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        #reference the output variable mailboxDynamoDbTableArn defined in provisioning-steps project (in the appropriate stage)
        ${cf:provisioning-steps-${opt:stage, self:provider.stage}.mailboxesDynamoDbTableArn} 
  
package:
  artifact: target/provisioning-steps-java.jar

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - http:
          path: ping
          method: get

          
stepFunctions:
  stateMachines:
    deletionStateMachine:
      name: deletionStateMachine
      events:
        - http:
            path: begin-deletion
            method: GET
      definition:
        Comment: "A fake engine, using Amazon States Language and Lambda"
        StartAt: Wait1
        States:
          Wait1:
            Type: Wait
            Seconds: 15
            End: true