# Make a copy of this file for each stage you deploy to, e.g. config-dev.yml

# The address you want CloudWatch alarm notification emails sent to
alarmNotificationEmail: name@email.com 

# The address Simple Email Service will send from (you will have to verify this address through AWS manually one time)
sesFromAddress: name@email.com

